### ISSUE TITLE
Incorrect width for Hangul Jamo Extended-B

### ISSUE THREAD

**Issue by ThomasDickey** [jquast/ucs-detect#9]
See this page on Unicode.org which lists several that are used as zero-width (ucs-detect says those are 2): [Hangul Jamo Extended-B](https://unicode.org/charts/nameslist/c_D7B0.html)

**Comment by jquast** [comment]
Wow! Hello @ThomasDickey big fan, thank you for the bug report!!

**Comment by jquast** [comment]
This is fixed by upgrade of wcwidth library, ``pip install --upgrade wcwidth`` I will try to make time to update the test results soon
